basePath: /api/v1
definitions:
  request.Detail:
    properties:
      amount:
        type: string
      description:
        type: string
      discount:
        type: number
      product_code:
        type: string
      tax:
        type: number
      unit_price:
        type: number
    type: object
  request.InvoiceInfo:
    properties:
      address:
        type: string
      emission_date:
        type: string
      identification:
        type: string
      identification_type:
        type: string
    type: object
  request.InvoiceRequest:
    properties:
      details:
        items:
          $ref: '#/definitions/request.Detail'
        type: array
      invoice_info:
        $ref: '#/definitions/request.InvoiceInfo'
      payments:
        items:
          $ref: '#/definitions/request.Payment'
        type: array
      tax_info:
        $ref: '#/definitions/request.TaxInfo'
    type: object
  request.Payment:
    properties:
      payment_form:
        type: string
      sales_time:
        type: integer
      total:
        type: number
      unit_time:
        type: string
    type: object
  request.TaxInfo:
    properties:
      business_name:
        type: string
      enviroment:
        type: string
      ruc:
        type: string
      sequencial:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: https://github.com/whacosta/API-Facturacion-Ecuador/issues
  description: Esta API, permite enviar a validar comprobantes de manera gratuita.
  termsOfService: http://swagger.io/terms/
  title: API Facturación Ecuador
  version: "1.0"
paths:
  /:
    get:
      responses: {}
      summary: Hello World Controller
  /invoice:
    post:
      consumes:
      - application/json
      parameters:
      - description: New invoice
        in: body
        name: invoice
        required: true
        schema:
          $ref: '#/definitions/request.InvoiceRequest'
      responses: {}
      summary: Generate New Invoice
      tags:
      - invoice
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
